services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes: [pgdata:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./backend:/code
      - ./storage:/storage
    depends_on: [postgres, redis]
    ports: ["8003:8000"]

  worker:
    build: ./backend
    command: celery -A app.tasks.celery_app.celery worker -l info -c 2
    env_file: .env
    volumes:
      - ./backend:/code
      - ./storage:/storage
    depends_on: [redis, postgres]

  frontend:
    build: ./frontend
    command: npm run dev
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports: ["3003:3000"]
    depends_on: [api]

volumes:
  pgdata:
